export default [
  {
    id: "upai",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "Upai",
  },
  {
    id: "taobao",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "Taobao",
  },
  {
    id: "cloudflare_v4",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "Cloudflare IPv4",
  },
  {
    id: "cloudflare_v6",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "Cloudflare IPv6",
  },
  {
    id: "ipify_v4",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "IPify IPv4",
  },
  {
    id: "ipify_v6",
    ip: "",
    country_name: "",
    region: "",
    city: "",
    latitude: "",
    longitude: "",
    isp: "",
    asn: "",
    asnlink: "",
    mapUrl: "res/img/defaultMap.jpg",
    showMap: false,
    source: "IPify IPv6",
  },
];
