export default {
  nav: {
    id: "nav",
    Title: "IP 工具箱",
    IPinfo: "IP 信息",
    Connectivity: "网络连通性",
    WebRTC: "WebRTC 测试",
    DNSLeakTest: "DNS 泄漏测试",
  },
  ipInfos: {
    id: "ipinfos",
    Title: "IP 信息",
    Notes:
      "将会从 6 个来源检查 IP 数据，如果当前 IP 栈只有 1 个，则没有数据的来源会显示为空。",
    Simple: "简约",
    Map: "地图",
    MapUnavailable: "地图不可用",
    Source: "来源",
    IP: "IP 地址",
    Country: "国家",
    Region: "地区",
    City: "城市",
    ISP: "ISP",
    ASN: "ASN",
    IPv4Error: "获取失败或不存在 IPv4 地址",
    IPv6Error: "获取失败或不存在 IPv6 地址",
  },
  connectivity: {
    id: "connectivity",
    Title: "网络连通性",
    Note: "通过加载对应网站上的小图片进行测试，延迟值仅供参考，实际会更小。",
    StatusWait: "待检测",
    StatusAvailable: "可用",
    StatusUnavailable: "不可用",
    StatusTimeout: "超时或不可用",
    checking: "检查中...",
  },
  webrtc: {
    id: "webrtc",
    Title: "WebRTC 测试",
    Note: "WebRTC 往往通过 UDP 直连进行建立，如果测试返回了真实 IP，则意味着你的代理设置没有覆盖这些连接。",
    StatusWait: "待检测或连接错误",
    StatusError: "测试出错",
  },
  dnsleaktest: {
    id: "dnsleaktest",
    Name: "测试",
    Title: "DNS 泄漏测试",
    Note: "DNS 泄露（DNS Leaks）的意思是，当你挂上 VPN/代理后，你解析域名时，依然通过当地的运营商进行解析，这时就有 DNS 泄露的风险。",
    Note2:
      "泄露测试的方法是通过访问新生成的域名，检测你是通过哪个地区的 DNS 出口进行解析，如果返回的出口区域和你当地的运营商区域相同，则有 DNS 泄露风险，你可能需要修改 VPN/代理设置。",
    Endpoint: "DNS 出口",
    EndpointCountry: "出口地区",
    StatusWait: "待检测",
    StatusError: "测试出错",
  },
  ipcheck: {
    id: "ipcheck",
    Title: "IP 查询",
    Placeholder: "请输入 IP 地址",
    Button: "查询",
    Error: "请输入有效的 IPv4 或 IPv6 地址。",
  },
  alert: {
    id: "alert",
    refreshEverythingMessage: "正在刷新所有数据，请等待...",
    refreshEverythingTitle: "正在刷新",
    OhNo: "糟糕！",
    Congrats: "恭喜呀！",
    OhNo_Message: "你当前似乎没有翻墙，部分内容无法显示。",
    Congrats_Message: "你当前已经翻墙，欢迎来到新世界。",
    maskedInfoTitle_1: "IP 隐藏成功",
    maskedInfoMessage_1: "IP 信息已隐藏，截图时请注意隐私。",
    maskedInfoTitle: "全部隐藏成功",
    maskedInfoMessage: "所有信息已隐藏，现在可以安心截图了。",
    unmaskedInfoTitle: "取消隐藏",
    unmaskedInfoMessage: "信息已显示，截图时请注意隐私。",

  },
  page: {
    title:
      "查看我的 IP 地址 | 查询本机 IP 地址及归属地 | 查看 WebRTC 连接 IP ｜ DNS 泄露检测 | Jason Ng 阿禅开源作品",
  },
  addBingMapKey: {
    Title: "添加 Bing Map API Key",
    Note: "添加后，可以在 IP 信息中显示地图。API Key 只会在当前浏览器中保存，方便下次使用，不会上传到服务器。",
    Placeholder: "请输入 Bing Map API Key",
    Button: "保存",
    removeButton: "删除",
    Error: "请输入有效的 Bing Map API Key。",
  },
};
